# Generated by Django 4.2.2 on 2023-07-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsale_app', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
