# Generated by Django 4.2.2 on 2023-07-08 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsale_app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
